---
title: '2020: o ano em que completei 22 anos'
date: '2020-11-08'
categories:
- Blogging
tags:
- Blogging
---

"2 Patinhos na Lagoa". Foi com esta frase que meu pai desejou-me um feliz aniversário na última quinta-feira. Não preciso comentar que este ano, 2020, deu uma "sacudida" em nossas vidas. Muitos eventos aconteceram neste ano - alguns muito bons e outros...nem tanto -, e gostaria de compartilhar uma pequena retrospectiva:

<!--more-->

"2 Patinhos na Lagoa". Foi com esta frase que meu pai desejou-me um feliz aniversário na última quinta-feira. Não preciso comentar que este ano, 2020, deu uma "sacudida" em nossas vidas. Muitos eventos aconteceram neste ano - alguns muito bons e outros...nem tanto -, e gostaria de compartilhar uma pequena retrospectiva:

# O Início do Ano

No geral, tive um ótimo início de ano. Viajei com a família, conheci lugares novos, novas pessoas, saí com amigos, me diverti. Aproveitei para estudar também - por meio de cursos no verão -, antes que as aulas da faculdade e o correrio do dia a dia retornassem. Por que estudar nas férias? Acho que é uma grande oportunidade para manter a chama viva sobre curso/faculdade/profissão que optei, além de ter contato com tópicos diferentes (ou abordagens diferentes) do que os abordados normalmente. Enfim, me faz bem :).

# A Pandemia

Infelizmente, nem tudo foram flores. No dia 15 de março, recebo um e-mail de um professor contendo esta [notícia](http://www.ufrgs.br/ufrgs/noticias/ufrgs-suspende-aulas-a-partir-desta-segunda-feira-dia-16-de-marco). SIM! A chegada da famosa pandemia do coronavírus (COVID-19), abalando a rotina de todos nós. Quarentena (ou *lockdown*), máscaras, álcool gel, evitar aglomerações, reduzir contatos físicos (abraços, beijos) tudo em prol da nossa proteção e da proteção do próximo. Alguns acharam bobagem no começo, outros continuam achando e ignorando as orientações dos profissionais. Os números começaram a crescer e são chocantes (basta olhar [aqui](https://covid.saude.gov.br/),  [aqui](https://mhbarbian.shinyapps.io/CovidMetrika/) e [aqui](https://mhbarbian.shinyapps.io/covid19_poa/)). Sou grato que eu e minha família estejamos bem, apesar da pandemia. Muitos perderam familiares, amigos, empregos e negócios. A luta para continuar não é fácil, então sejamos todos fortes e façamos nosso melhor, dentro do possível e da necessidade.  

# Ensino Remoto Emergencial - ERE

No final de julho, a UFRGS lança a seguinte [notícia](https://www.ufrgs.br/dequi/noticias/ufrgs-regulamenta-o-ensino-remoto-emergencial-ere/), informando que nossas aulas retornariam. Conversamos com alguns professores sobre o assunto, e achei muito legal o motivo do nome:

> Não chamamos de EAD - Ensino À Distância, pois ele é planejado. O ERE é uma forma alternativa de retornarmos às atividades considerando a situação extraodionária. Teremos todos que nos adaptar.

Maiores detalhes [aqui](https://www.ufrgs.br/prograd/ere-ensino-remoto-emergencial/). Minha adaptação foi relativamente tranquila, mas foi nítido os desafios enfrentados por diversos estudantes e professores: entender plataformas, gravação de aulas, encontros remotos, preparação de material, organizar rotina, espaço para estudo, administrar tempo, etc. Admito que até gostei um pouco: o fato de não ter o tempo de deslocamento e aulas gravadas (majoritariamente) ajudaram muito a poder ver (e rever) aulas e materias, bem como revisar ou ficar em dia com a matéria atrasada hehe.

# Reta Final

Claro! Não tem sido simples ou fácil lidar com toda a presente realidade. Procuro me adaptar e, principalmente, SEGUIR EM FRENTE! Falta pouco para terminar 2020, o ano da pandemia do coronavírus, o ano em que fiz um dos melhores cursos da minha vida, o ano em que completei meus 22 anos. 

Bem...era isso! Escrevi este post como uma forma de "colocar os pensamentos no papel". Foi bastante pessoal, um relato/desabafo próprio. Não é fácil e nem simples. Admito que tenho bastante medo da situação ainda. Mesmo assim, sigo em frente. Por quê? Acredito que dias melhores virão.